config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :bets do
    resource :winners
    resources :participations, only: [:new, :create]
    collection do
      get :paginate
      get :partial_bet_show
    end
  end

  resources :participations, only: [:destroy]
  
  resources :choices
  resources :users do
    resources :friendship_requests, only: [:create]
    resources :friendships, only: [:create]
    member do
      get :sync_calendar
      get :redirect
      get :callback
      get :history
    end
  end

  resources :friendship_requests, only: [:destroy]
  resources :friendships, only: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  # post "api/v1/user" => "api#v1#users#create"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :bets, only: [:index, :show, :create, :destroy] do
        resources :participations, only: [:create]
      end
      resources :participations, only: [:destroy]
      resources :choices, only: [:create, :destroy]
    end
  end

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
	validates :amount, presence: true, numericality: { greater_than: 0 }, allow_blank: false
	validates_uniqueness_of :user_id, scope: [:bet_id]

	belongs_to :user
	belongs_to :choice
	belongs_to :bet
	validate :amount_range, :valid_user, :valid_choice, :sufficient_balance

	after_destroy :return_balance
	after_create :remove_balance

	scope :active, -> { joins(:bet).where('"bets"."deadline" > ?', [Date.today]) }
	scope :closed, -> { joins('JOIN winners on participations.bet_id = winners.bet_id') }

	def valid_user
		if user_id == self.bet.user.id
			errors.add(:user_id, "cannot be the creator of the bet")
		elsif user.role != 'regular'
			errors.add(:user_id, "must be a regular user")
		end
	end

	def valid_choice
		if bet_id != self.choice.bet_id
			errors.add(:choice_id, "must belong to the specified bet")
		end
	end

	def amount_range
		if amount < self.bet.min_bet or amount > self.bet.max_bet
			errors.add(:amount, "out of range specified in bet")
		end
	end

	def valid_date
		if self.bet.deadline.to_date.past?
			errors.add(:bet, "deadline has been met and you can no longer participate.")
		end
	end

	def sufficient_balance
		if self.user.balance < self.amount
			errors.add(:user, "has insufficient balance.")
		end
	end

	def return_balance
      user = self.user
      user.balance += self.amount
      user.save
    end

    def remove_balance
      user = self.user
      user.balance -= self.amount
      user.save
    end

end

app/controllers/api/v1/participations_controller.rb
module Api::V1
	class ParticipationsController < ApiController
		before_action :authenticate, only: [:create, :destroy]


		def create
		    @bet = Bet.find(params[:bet_id])
		    params[:user_id] = @current_user.id
		    @participation = @bet.participations.build(participation_params)
		    unless @participation.save
		    	render json: { errors: @participation.errors }, status: :unprocessable_entity
		    end
		end
		
		def destroy
			participation = Participation.find(params[:id])
			user = participation.user
			if @current_user == user or ['admin'].include?(@current_user.role)
				participation.destroy
				render json: { sucess: "Participation destroy" }, status: 200
			else
				render json: { errors: "current_user different to participation" }, status: :unprocessable_entity
			end
		end

		private
		
			def participation_params
		      params.permit(:amount,:user_id,:choice_id,:bet_id)
		    end
	end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  include Secured
  before_action :logged_in?, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_participation, only: [:show, :edit, :update, :destroy, :winnings]
  before_action :valid_date, only: [:new, :create, :edit, :upate, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @bet = Bet.find(params[:bet_id])
    @participation = @bet.participations.build
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @bet = Bet.find(params[:bet_id])
    params[:participation][:user_id] = current_user.id
    @participation = @bet.participations.build(participation_params)
    respond_to do |format|
      if @participation.save
        format.html { redirect_to bets_url, notice: 'You are now participating in this bet.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new, status: 422 }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_back(fallback_location: @bet, notice: 'Participation was successfully updated.') }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @bet = @participation.bet
    @participation.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: @bet, notice: 'You are no longer participating in this bet.') }
      format.json { head :no_content }
    end
  end

  def self.winnings(participation)
    if participation.bet.winning_choice
      bet = participation.bet
      if participation.choice == bet.winning_choice
        pool = 0
        bet.participations.where('participations.choice_id != ?', bet.winning_choice.id).pluck(:amount).each do |amount|
          pool += amount
        end
        winners_sum = 0
        bet.participations.where(choice: bet.winning_choice).pluck(:amount).each do |amount|
          winners_sum += amount
        end
        participation_winnings = pool.to_f() * (participation.amount.to_f()/winners_sum.to_f())
        participation_winnings.to_i()
      else
        - participation.amount
      end
    else
      - participation.amount
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:amount,:user_id,:choice_id,:bet_id)
    end

    def valid_date
      if @participation
        bet = @participation.bet
      else
        bet = Bet.find(params[:bet_id])
      end
      unless bet.deadline.future? or bet.deadline == Date.today
        redirect_back(fallback_location: bet, alert: "Bet is no longer active")
        return
      end
    end
end

app/helpers/api/v1/participations_helper.rb
module Api::V1::ParticipationsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for([@bet, @participation]) do |f| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Choose an amount: <span id="bet_amount"><%= @bet.min_bet %></span></h2>
  <div class="field">
    <div class="slider">
      <%= f.range_field :amount, in: @bet.min_bet..@bet.max_bet, oninput: 'update_amount()', value: @bet.min_bet %>
    </div>
  </div>

  <h2>Make your choice:</h2>
  <div class="field">
    <%= f.collection_radio_buttons(:choice_id, @bet.choices, :id, :value, checked: @bet.choices.first.id) do |b| %>
      <div class="radio">
        <%= b.radio_button %>
        <%= b.label do %>
          <%= b.text %>
        <% end %>
        <img src=<%= image_url('check.png') %>></img>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Place bet" %>
  </div>

<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>
<div class="form_page">
<%= render 'form', participation: @participation %>
</div>
<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Username</th>
      <th>Choice</th>
      <th>Bet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.amount %></td>
        <td><%= participation.user.name %></td>
        <td><%= participation.choice.value %></td>
        <td><%= participation.bet.name %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/participations/new.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "update_amount.js" %>
<% end %>
<div class="form_page">
<h1>Betting on: <%= @participation.bet.name %></h1>

<%= render 'form', participation: @participation %>
</div>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @participation.amount %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>