config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :bets do
    resource :winners
    resources :participations, only: [:new, :create]
    collection do
      get :paginate
      get :partial_bet_show
    end
  end

  resources :participations, only: [:destroy]
  
  resources :choices
  resources :users do
    resources :friendship_requests, only: [:create]
    resources :friendships, only: [:create]
    member do
      get :sync_calendar
      get :redirect
      get :callback
      get :history
    end
  end

  resources :friendship_requests, only: [:destroy]
  resources :friendships, only: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  # post "api/v1/user" => "api#v1#users#create"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :bets, only: [:index, :show, :create, :destroy] do
        resources :participations, only: [:create]
      end
      resources :participations, only: [:destroy]
      resources :choices, only: [:create, :destroy]
    end
  end

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/choice.rb
class Choice < ApplicationRecord
	validates :value, presence: true, length: { minimum: 6 }, allow_blank: false
	validates_uniqueness_of :value, scope: [:bet_id]

	belongs_to :bet, optional: true
	has_many :participation
	has_one :winner
end

app/controllers/api/v1/choices_controller.rb
module Api::V1
	class ChoicesController < ApiController
		before_action :authenticate, only: [:create, :destroy]


		def create
		    @bet = Bet.find(params[:bet_id])
			if ['admin','mod'].include?(@current_user.role) or @current_user == @bet.user
			    choice = Choice.new(choice_params)
			    unless choice.save
			    	render json: { errors: @participation.errors }, status: :unprocessable_entity
			    end
			else
				render json: { errors: 'Unauthorized access!' }, status: 401
			end
		end

		def destroy
			choice = Choice.find(params[:id])
			@bet = choice.bet
			if ['admin','mod'].include?(@current_user.role) or @current_user == @bet.user
				choice.destroy
			else
				render json: { errors: 'Unauthorized access!' }, status: 401
			end
		end


		private

		def choice_params
	      params.permit(:value,:bet_id)
	    end

	    def is_admin
	      if @current_user
	        ['admin','mod'].include?(@current_user.role)
	      end
	    end
	end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  include Secured
  before_action :logged_in?, only: %i[new create edit update destroy]
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  def create_1
    params[:choices].each do |choice_params|
      @choice = Choice.new(choice_params)
      if not @choice.save
        format.html { render :new, status: 422 }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new, status: 422 }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:value,:bet_id)
    end
end

app/helpers/api/v1/choices_helper.rb
module Api::V1::ChoicesHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(choice) do |f| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value, required: true %>
  </div>

  <div class="field">
    <%= f.label :bet_id %>
    <%= f.select :bet_id, Bet.all.collect { |bet| [ bet.name, bet.id ] }, { include_blank: true }, { required: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Bet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.value %></td>
        <td><%= choice.bet.name %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @choice.value %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>