config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :bets do
    resource :winners
    resources :participations, only: [:new, :create]
    collection do
      get :paginate
      get :partial_bet_show
    end
  end

  resources :participations, only: [:destroy]
  
  resources :choices
  resources :users do
    resources :friendship_requests, only: [:create]
    resources :friendships, only: [:create]
    member do
      get :sync_calendar
      get :redirect
      get :callback
      get :history
    end
  end

  resources :friendship_requests, only: [:destroy]
  resources :friendships, only: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  # post "api/v1/user" => "api#v1#users#create"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :bets, only: [:index, :show, :create, :destroy] do
        resources :participations, only: [:create]
      end
      resources :participations, only: [:destroy]
      resources :choices, only: [:create, :destroy]
    end
  end

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bet.rb
class Bet < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3 }, allow_blank: false
	validates :description, presence: true, length: { minimum: 10 }, allow_blank: false
	validates :deadline, presence: true, allow_blank: false
	validates :max_participants, presence: true, allow_blank: false, numericality: { greater_than: 1 }
	validates :min_bet, presence: true, allow_blank: false, numericality: { greater_than: 1 }
	validates :max_bet, presence: true, allow_blank: false,
	numericality: { greater_than: 0, greater_than_or_equal_to: :min_bet }
	validates_uniqueness_of :name, scope: [:deadline]
	validate :deadline_is_in_future

	belongs_to :user
	has_many :choices, dependent: :destroy
	has_many :participations, dependent: :destroy
	accepts_nested_attributes_for :choices
	has_one :winner
	has_one :winning_choice, through: :winner, source: :choice

	scope :active, -> { where("bets.deadline > ?", Date.today) }
	scope :closed, -> { joins(:winner).where(winner_id: nil) }
	scope :not_private, -> { where('bets.private': false) }
	scope :not_owned, lambda { |dude| where("bets.user_id != ?", dude.id) }
	scope :bettable, lambda { |dude| active.not_owned(dude).not_private }
	scope :bettable_private, lambda { |dude| joins('JOIN friendships ON bets.user_id = friendships.user_id').where('friendships.friend_id = ? and bets.private = true', dude.id) }
	# scope :accessible, lambda { |dude| where('user_id = ?', dude.id).merge(bettable(dude)).merge(bettable_private(dude)) }

	def deadline_is_in_future
		if deadline.to_date.past? or deadline.today?
			errors.add(:deadline, "can't be in the past")
		end
	end
end

app/controllers/api/v1/bets_controller.rb
module Api::V1
	class BetsController < ApiController
		before_action :authenticate, only: [:create, :destroy]


		def index
			@bets = Bet.all
		end

		def show
			@bet = Bet.find(params[:id])
		end

		def create
		    params[:user_id] = @current_user.id
		    @bet = Bet.new(bet_params)
		    unless @bet.save
		    	render json: { errors: @participation.errors }, status: :unprocessable_entity
		    end
		end
		def destroy
			@bets = Bet.all
			@bet = Bet.find(params[:id])
			if ['admin','mod'].include?(@current_user.role) or @current_user == @bet.user
			    @bet.participations.each do |part|
			      part.destroy
			    end
			    @bet.destroy
			else
				render json: { errors: 'Unauthorized access!' }, status: 401
			end
		end

		private


		def bet_params
	      params.permit(:name, :description, :deadline, :max_participants, :kind, :min_bet, :max_bet, :user_id,:private)
	    end
	end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  include Secured
  before_action :logged_in?, only: %i[new create edit update destroy]
  before_action :set_bet, only: [:show, :edit, :update, :destroy]
  before_action :can_view?, only: [:show, :edit, :update, :destroy]
  before_action :is_owner?, only: [:edit, :update]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def paginate
    pp = params[:pp].to_i()-1
    pl = params[:pl].to_i()
    first_bet = pp*pl
    last_bet = first_bet + pl - 1
    puts 'first'
    puts first_bet
    puts 'last'
    puts last_bet

    @bets = Bet.all

    if not current_user
      bet_list = @bets.active.not_private.sort_by {|bet| bet.deadline}[first_bet..last_bet]
    elsif current_user and current_user.role == 'regular'
      bet_list = @bets.bettable(current_user).sort_by {|bet| bet.deadline}[first_bet..last_bet]
    else
      bet_list = @bets.active.sort_by {|bet| bet.deadline}[first_bet..last_bet]
    end
    respond_to do |format|
      format.html { redirect_back(fallback_location: bets_path, notice: "Success") }
      format.json do
        render json: {
          bet_list: bet_list.pluck(:id),
          page: params[:pp]
        }
      end
    end
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  def partial_bet_show
    bets = params[:bets]
    render(partial: "show", locals: {ids: bets})
  end

  # GET /bets/new
  def new
    @bet = Bet.new
    @bet.choices.build
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    params[:bet][:user_id] = current_user.id
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new, status: 422 }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.participations.each do |part|
      part.destroy
    end
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bet_range(page_number, bets_per_page)
    if not current_user
      bet_list = @bets.active.not_private.sort_by {|bet| bet.deadline}[page_number-1..page_number*bets_per_page]
    elsif current_user and current_user.role == 'regular'
      bet_list = @bets.bettable(current_user).sort_by {|bet| bet.deadline}[page_number-1..page_number*bets_per_page]
    else
      bet_list = @bets.active.sort_by {|bet| bet.deadline}[page_number-1..page_number*bets_per_page]
    end
    respond_to do |format|
      format.html { redirect_back(fallback_location: bets_path, notice: "Success") }
      format.json do
        render json: {
          bet_list: bet_list
        }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    def is_owner?
      redirect_to @bet, alert: "Unauthorized access!" unless @bet.user == current_user or current_user.role != 'regular'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:name, :description, :deadline, :max_participants, :kind, :min_bet, :max_bet, :user_id, :private, :value, :p, :pl, choices_attributes: [:value])
    end

    def can_view?
      if @bet.private
        redirect_to root_path, alert: "Unauthorized access!" unless current_user and (@bet.user == current_user or current_user.role != 'regular' or @bet.user.friends.include?(current_user))
      end
    end
end

app/helpers/api/v1/bets_helper.rb
module Api::V1::BetsHelper
end

app/helpers/bets_helper.rb
module BetsHelper


	def participate_button(bet)
		return unless current_user
		return if bet.user == current_user
		return if current_user.role != 'regular'
		return if bet.deadline.to_date.past? or bet.deadline == Date.today
		friendship = current_user.friendships.detect do |relation|
			relation.friend_id == bet.user.id
		end
		participation = bet.participations.detect do |participation|
			participation.user.id == current_user.id
		end
		if bet.private and not(friendship)
			return
		end
		if participation
			link_to 'Withdraw', participation_path(participation), method: 'delete', class: 'delete'
		else
			link_to 'Participate', new_bet_participation_path(bet), class: 'round_button'
		end
	end

	def close_button(bet)
	 	return unless current_user 
	 	return unless current_user.role == 'admin' or bet.user == current_user or current_user.role == 'mod'
	 	return if has_winner(bet)
	 	if bet.deadline.to_date.past?
	 		link_to 'Close', new_bet_winners_path(bet), class: 'delete'
	 	end
	end

	def has_winner(bet)
		return bet.winner
	end

	def percentage_and_winnings(choice)
		participants = choice.bet.participations.count
		return unless participants > 0
		votes_for_this = choice.bet.participations.where(choice: choice).count
		percentage = (votes_for_this.to_f()/participants.to_f())*100
		total = 0
		choice.bet.participations.where.not(choice_id: choice.id).each do |parti|
			total += parti.amount
		end
		total
		winnings = total/(1 + choice.bet.participations.where(choice_id: choice.id).count)
		'(' + percentage.to_i().to_s() + '% of votes, ' + winnings.to_s() + ' points expected winnings)'
	end

	def page_numbers(bets_per_page=5)
		if not current_user
			bet_count = @bets.active.not_private.count
		elsif current_user and current_user.role == 'regular'
			bet_count = @bets.bettable(current_user).count
		else
			bet_count = @bets.active.count
		end
		if bet_count >= 1
			page_count = 1 + (bet_count-1)/bets_per_page
			puts 'total bets'
			puts bet_count
			final_string = "<div class='page_list'> "
			final_string += link_to '<<', { controller: 'bets', action: 'paginate', pp: 1, pl: bets_per_page }, remote: true, class: 'round_button pagination', data: { type: 'json' }
			(1..page_count).each do |page_number|
				final_string += link_to page_number, { controller: 'bets', action: 'paginate', pp: page_number, pl: bets_per_page }, remote: true, class: 'round_button pagination page_'+page_number.to_s(), data: { type: 'json' }
			end
			final_string += link_to '>>', { controller: 'bets', action: 'paginate', pp: page_count, pl: bets_per_page }, remote: true, class: 'round_button pagination', data: { type: 'json' }
			final_string += "</div>"
			return raw(final_string)
		end
	end

end

app/views/bets/_form.html.erb
<%= form_for(bet) do |f| %>
  <% if bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_content">

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, required: true %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_select :deadline, required: true %>
  </div>

  <div class="field">
    <%= f.label :max_participants %>
    <%= f.number_field :max_participants, required: true %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.text_field :kind, required: true %>
  </div>

  <div class="field">
    <%= f.label :min_bet %>
    <%= f.number_field :min_bet, required: true %>
  </div>

  <div class="field">
    <%= f.label :max_bet %>
    <%= f.number_field :max_bet, required: true %>
  </div>

  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

  <div class="values">
    <div class="field">
      <%= f.label "Choice" %>
      <input required="required" type="text" name="bet[choices_attributes][][value]">
    </div>
    <div class="field">
      <%= f.label "Choice" %>
      <input required="required" type="text" name="bet[choices_attributes][][value]">
    </div>
  </div>
  
    <button class="add_form_field round_button">Add another choice &nbsp; <span style="font-size:16px; font-weight:bold;">+ </span></button>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/bets/_participate.html.erb
<%= form_for(@participation), url: new_bet_participations_path(@bet) do |f| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount, required: true %>
  </div>

  <div class="field">
    <%= f.label :choice_id %>
    <%= f.select :choice_id, @bet.choices.collect { |choice| [ choice.value, choice.id ] }, { include_blank: true }, { required: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/bets/_show.html.erb
<% ids.each do |id| %>
  <% bet = Bet.find(id) %>
      <div class="bet_block">
        <button class="toggle_details", onclick="toggleblock(<%= bet.id %>)">
          <div class="summary", id="summary_<%= bet.id %>">
            <table>
              <tr>
              <td class="index_name"><%= bet.name %></td>
              <td class="index_deadline">Deadline: <%= bet.deadline %></td>
              <td class="index_slots">Free slots: <%= bet.max_participants - bet.participations.count %></td>
              <td class="index_min">Min bet: <%= bet.min_bet %></td>
              <td class="index_max">Max bet: <%= bet.max_bet %></td>
              <% if current_user %>
                <td class="index_author">Created by: <%= bet.user.name %></td>
              <% end %>
              </tr>
            </table>
          </div>
        </button>
        <div class="details", id="content_<%= bet.id %>">
  <div class="bet_show">
  <div class="info">
  <p>
    <strong>Description:</strong>
    <%= bet.description %>
  </p>
  </div>

  <div class="info">
  <p>
    <strong>Choices:</strong>
    <ul>
      <% bet.choices.each do |choice| %>
        <li><%= choice.value %> <%= percentage_and_winnings(choice) %></li>
      <% end %>
    </ul>
  </p>
  </div>

  <div class="info">
  <p>
    <strong>Max participants:</strong>
    <%= bet.max_participants %>
  </p>
  </div>

  <div class="info">
  <p>
    <strong>Kind:</strong>
    <%= bet.kind %>
  </p>
  </div>

  <% if bet.participations.count > 0 and current_user %>
  <div class="info">
  <p>
    <strong>Participants:</strong>
    <ul>
      <% bet.participations.each do |parti| %>
        <li><%= parti.user.name %></li>
      <% end %>
    </ul>
  </p>
  </div>
  <% end %>

  <%= participate_button(bet) %>

  <% if has_winner(bet)%>
    <p>
      <strong>Winner choice:</strong>
      <%= bet.winner.choice.value %>
    </p>
  <%else%>
    <%= close_button(bet) %>
  <%end%>
  </div>
  </div>
  </div>
<% end %>

app/views/bets/edit.html.erb
<div id='form_page'>
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>
</div>

app/views/bets/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "toggle_bet.js" %>
<% end %>
<h1>Bets</h1>
<%= link_to 'New Bet', new_bet_path, class: "round_button" if current_user %>
<div class="bet_list">

  <% if not current_user %>
    <% all_bets = @bets.active.not_private %>
  <% elsif current_user and current_user.role == 'regular' %>
    <% all_bets = @bets.bettable(current_user) %>
    <% private_bets = @bets.bettable_private(current_user) %>
  <% else %>
    <% all_bets = @bets.active %>
  <% end %>

  <% if current_user and current_user.role == 'regular' and private_bets.count > 0 %>
  <h2>Private bets</h2>
    <% private_bets.sort_by {|bet| bet.deadline}.each do |bet| %>  
      <%= render partial: "show", locals: { ids: [bet.id] } %>
    <% end %>
    <h2>Public bets</h2>
  <% end %>

  <%= page_numbers() %>
  <div id="public_bets">
    <% all_bets.sort_by {|bet| bet.deadline}[0 .. 4].each do |bet| %>
      <%= render partial: "show", locals: { ids: [bet.id] } %>
      <% if current_user and current_user.role == 'admin' %>
        <%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
      <% end %>
    <% end %>
  </div>
  <%= page_numbers() %>
</div>

app/views/bets/index1.html.erb
<h1>Bets</h1>
<%= link_to 'New Bet', new_bet_path, class: "round_button" if current_user %>

<table class="index-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Deadline</th>
      <th>Available spaces</th>
      <th>Min bet</th>
      <th>Max bet</th>
      <th>Creator</th>
      <% if current_user and current_user.role == 'admin' %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @bets.sort_by {|bet| bet.deadline}.each do |bet| %>
      <tr>
        <td><%= link_to bet.name, bet %></td>
        <td><%= bet.deadline %></td>
        <td><%= bet.max_participants - bet.participations.count %></td>
        <td><%= bet.min_bet %></td>
        <td><%= bet.max_bet %></td>
        <td><%= bet.user.name %></td>
        <% if current_user and current_user.role == 'admin' %>
          <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bets/new.html.erb
<div id='new_bet_page' class='form_page'>
<h1>New Bet</h1>

<%= render 'form', bet: @bet %>

<div><%= link_to 'Back', bets_path, class: 'round_button delete' %></div>
</div>

app/views/bets/show.html.erb
<div class="bet_show">

<p>
  <strong>Name:</strong>
  <%= @bet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bet.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @bet.deadline %>
</p>

<p>
  <strong>Max participants:</strong>
  <%= @bet.max_participants %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @bet.kind %>
</p>

<p>
  <strong>Minimum bet:</strong>
  <%= @bet.min_bet %>
</p>

<p>
  <strong>Maximum bet:</strong>
  <%= @bet.max_bet %>
</p>

<p>
  <strong>Choices:</strong>
  <ul>
    <% @bet.choices.each do |choice| %>
      <li><%= choice.value %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Participants:</strong>
  <ul>
    <% @bet.participations.each do |parti| %>
      <li><%= parti.user.name %></li>
    <% end %>
  </ul>
</p>
<%= participate_button(@bet) %>

<% if has_winner(@bet)%>
  <p>
    <strong>Winner choice:</strong>
    <%= @bet.winner.choice.value %>
  </p>
<%else%>
  <%= close_button(@bet) %>
<%end%>
</div>