config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :bets do
    resource :winners
    resources :participations, only: [:new, :create]
    collection do
      get :paginate
      get :partial_bet_show
    end
  end

  resources :participations, only: [:destroy]
  
  resources :choices
  resources :users do
    resources :friendship_requests, only: [:create]
    resources :friendships, only: [:create]
    member do
      get :sync_calendar
      get :redirect
      get :callback
      get :history
    end
  end

  resources :friendship_requests, only: [:destroy]
  resources :friendships, only: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  # post "api/v1/user" => "api#v1#users#create"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :bets, only: [:index, :show, :create, :destroy] do
        resources :participations, only: [:create]
      end
      resources :participations, only: [:destroy]
      resources :choices, only: [:create, :destroy]
    end
  end

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ludopath</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'logo.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript_includes %>
  </head>

  <body>
  	<header>
      <div id="logo">
        <%= link_to root_path do %>
          <img src=<%= image_url('logo.png') %>/>
        <% end %>
      </div>

        <nav id="main-menu">
          <% if current_user %>
            <%= link_to 'Users', users_path %>
          <% end %>
          <%= link_to 'Bets', bets_path %>
        </nav>

      <div id="user-bar">
  			<% if current_user %>
          <div class="name">Welcome, <%= link_to current_user.name, current_user %><br>Balance: <%= current_user.balance %>
          </div>
				<%= link_to 'Logout', session_url, method: :delete%><br>
  			<% else %>
          <table>
            <tbody>
              <td>
                <%= render 'sessions/form', session: @session %>
              </td>
              <td>
                <%= link_to 'Sign up', new_user_url %>
              </td>
            </tbody>
          </table>
  			<% end %>
  		</div>

  	</header>

  	<main>
  		<% flash.each do |type, message| %>
    		<div id="<%= type %>", class="flash"><%= message %></div>
    	<% end %>
      <div id="content">
        <%= yield %>
      </div>
    </main>

    <footer>
      <hr>
      <div id='app_name'>© Ludopath 2017</div>
    </footer>
  </body>
</html>